version: "2.4"
services:
  webssh:
    image: docker.io/austozi/webssh:latest
    container_name: webssh
    restart: unless-stopped
    volumes:
      - ./config/log:/config/log
    expose:
      - 8888
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.42.0/29
