FROM python:3.7-slim

LABEL maintainer=austozi

RUN apt-get -qq update && \
    apt-get -yy install \
        build-essential \
        libssl-dev \
        libffi-dev \
        python3-dev \
        rustc

RUN pip3 install --upgrade pip

RUN pip3 install \
  paramiko==2.7.2 \
  tornado==6.0.4

RUN pip3 install webssh

RUN mkdir -p /config/log

EXPOSE 8888

ENTRYPOINT "wssh" "--log-file-prefix=/config/log/wssh.log" "--port=8888" "--logging=info"

CMD ["wssh", "--log-file-prefix=/config/log/wssh.log", "--port=8888", "--logging=info"]
