version: "3"
services:
  webssh:
    image: "austozi/webssh:latest"
    container_name: "webssh"
    restart: "unless-stopped"
    volumes:
      - "./config/log:/config/log"
    expose:
      - 8888
    networks:
      - "proxy"
networks:
  proxy:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.16.56.0/29"
