version: "3"
services:
  webssh:
    image: austozi/webssh:latest
    container_name: webssh
    restart: unless-stopped
    expose:
      - 8888
    networks:
      - swag_default
networks:
  swag_default:
    external: true
