services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    restart: unless-stopped
    environment:
      PORT: 5000
      PUID: 1000
      PGID: 1000
      BASE_URL: https://changedetection.example.com # Change me
      USE_X_SETTINGS: 1
      WEBDRIVER_URL: http://changedetection_selenium:4444/wd/hub
    volumes:
      - ./config:/datastore
    expose:
      - 5000
    networks:
      - backend
      - frontend
  selenium:
    image: docker.io/selenium/standalone-chrome:115.0
    container_name: changedetection_selenium
    restart: unless-stopped
    shm_size: "2g"
    environment:
      TZ: Europe/London
    expose:
      - 4444
      - 7900s
    networks:
      - backend
networks:
  backend:
  frontend:
