version: "3"
services:
  ulogger:
    image: austozi/ulogger-server:latest
    container_name: ulogger
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/London
      - ULOGGER_LANG=en_GB.utf-8
      # Specify admin user name here (default = admin)
      #- ULOGGER_ADMIN_USER=
      - ULOGGER_DB_DRIVER=sqlite
    volumes:
      - ./config:/data
    expose:
      - 80
    networks:
      - swag_default
networks:
  swag_default:
    external: true
