version: "3"
services:
  roundcube:
    image: docker.io/austozi/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    environment:
      TZ: Europe/London
      ROUNDCUBEMAIL_DEFAULT_HOST: mail.example.com
      ROUNDCUBEMAIL_SMTP_SERVER: smtp.example.com
      ROUNDCUBEMAIL_DEFAULT_PORT: 993
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_PLUGINS: archive,zipdownload,twofactor_gauthenticator,fail2ban
      ROUNDCUBEMAIL_SKIN: elastic
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 10M
      ROUNDCUBEMAIL_DB_TYPE: sqlite
    volumes:
      - ./config/db:/var/roundcube/db
      - ./config/www:/var/www/html
    expose:
      - 80
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.32.0/29
