version: "3"
services:
  mealie:
    image: docker.io/hkotel/mealie:latest
    container_name: mealie
    restart: unless-stopped
    environment:
      TZ: Europe/London
      DB_ENGINE: sqlite
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "true"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "false"
      RECIPE_DISABLE_AMOUNT: "false"
      WEB_CONCURRENCY: 4
      WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 1
    expose:
      - 80
    volumes:
      - ./config:/app/data
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.23.0/29
