version: "3"
services:
  duckdns:
    image: "linuxserver/duckdns:latest"
    container_name: "duckdns"
    restart: "unless-stopped"
    environment:
      PUID: 1000 #optional
      PGID: 1000 #optional
      TZ: "Europe/London"
      SUBDOMAINS: "domain1,domain2"
      TOKEN: "<get-token-from-duckdns-account>"
        LOG_FILE: "true" #optional
    volumes:
      - "./config:/config"
    networks:
      - "backend"
networks:
  backend:
    driver: "bridge"
    ipam:
      config:
      - subnet: "172.16.5.0/30"
