services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      TZ: Europe/London
    volumes:
      - ./config:/config
      - ./data:/metadata
    expose:
      - 80
    networks:
      - frontend
networks:
  frontend:
