version: "3"
services:
  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      TZ: Europe/London
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      ADMIN_TOKEN: ChangeMe # Change token for accessing admin interface
      LOG_FILE: /data/log/vaultwarden.log
      LOG_LEVEL: info
    volumes:
      - ./config:/data
    expose: 
      - 80
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.40.0/29
