version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 81:80/tcp
    environment:
      - TZ=Europe/London
      # Specify own password, or Pi-hole will assign a random one:
      #- WEBPASSWORD=
      # Set upstream DNS to Cloudflare:
      - PIHOLE_DNS=1.1.1.3;1.0.0.3
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      - swag_default
networks:
  swag_default:
    external: true
