services:
  server:
    image: codeberg.org/forgejo/forgejo:7
    container_name: forgejo
    restart: unless-stopped
    environment:
      TZ: Europe/London
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ./config:/data
    expose:
      - 3000
      #- 22 # Uncomment to enable SSH access
    networks:
      - frontend
networks:
  frontend:
