version: "3"
services:
  nextcloud:
    image: "linuxserver/nextcloud:22.2.2" # Upgrade manually
    container_name: "nextcloud"
    restart: "unless-stopped"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      DB_HOST: "nextcloud_db"
      DB_USERNAME: "nextcloud"
      DB_PASSWORD: "SUPER_SECRET_PASSWORD" # Change me
      DB_DATABASE: "nextcloud"
    volumes:
      - "./config:/config"
      - "./data:/data"
    expose:
      - 443
    depends_on:
      - "db"
      - "redis"
    networks:    
      - "backend"
      - "mailer"
      - "proxy"
  db:
    image: "yobasystems/alpine-mariadb:10.5.9" # Upgrade manually
    container_name: "nextcloud_db"
    restart: "unless-stopped"
    environment:
      TZ: "Europe/London"
      MYSQL_ROOT_PASSWORD: "SUPER_SECRET_ROOT_PASSWORD" # Change me
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "SUPER_SECRET_PASSWORD" # Change me
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_general_ci"
    expose:
      - 3306
    volumes:
      - "./mariadb:/var/lib/mysql"
    networks:
      - "backend"
  redis:
    image: "redis:alpine"
    container_name: "nextcloud_redis"
    restart: "unless-stopped"
    expose:
      - 6379
    networks:
      - "backend"
networks:
  proxy:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.16.16.0/29"
  mailer:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.17.0/29"
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.18.0/29"
