---
version: "3"
services:
  nextcloud:
    image: docker.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DB_HOST=nextcloud_db
      - DB_USERNAME=nextcloud
      - DB_PASSWORD=change_me
      - DB_DATABASE=nextcloud
    volumes:
      - ./config:/config
      - ./data:/data
    expose:
      - 443
    depends_on:
      - db
      - redis
  db:
    image: docker.io/yobasystems/alpine-mariadb:10.5.9
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
      - TZ=Europe/London
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=change_me
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    volumes:
      - ./mariadb:/var/lib/mysql
    expose:
      - 3306
  redis:
    image: docker.io/redis:alpine
    container_name: nextcloud_redis
    hostname: nextcloud_redis
    restart: unless-stopped
    expose:
      - 6379
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.18.0/27
