version: "3"
services:
  nextcloud:
    # Change tag manually to upgrade
    image: linuxserver/nextcloud:22.2.2
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DB_HOST=nextcloud_db
      - DB_USERNAME=nextcloud
      - DB_PASSWORD=Super-Secret-Password1
      - DB_DATABASE=nextcloud
    volumes:
      - ./config:/config
      - ./data:/data
    expose:
      - 443
    depends_on:
      - db
      - redis
    networks:
      - default
      - swag_default
      - mailserver_default
  db:
    # Change tag manually to upgrade
    image: yobasystems/alpine-mariadb:10.5.9
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=Super-Secret-Password2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Super-Secret-Password1
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    expose:
      - 3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - default
  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.11.0/27
  swag_default:
    external: true
  mailserver_default:
    external: true
