version: "3"
services:
  calibreweb:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibreweb:calibre
    volumes:
      - ./config:/config
      - ./data:/books
    expose:
      - 8083
    networks:
      - proxy
      - mailer
networks:
  proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.9.0/29
  mailer:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/29
