- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes    
      
  - name: Install packages
    package:
      name:
        - ansible
        - curl
        - docker-ce        
        - docker-compose
        - git
        - jq
        - python3-pip
      state: latest    
      
  - name: Install/Update Python modules
    pip:
      name:
        - lastversion
        - pip
        - yt-dlp
      state: latest

  - name: Schedule maintenance
    cron:
      name: "Hourly ansible-pull config"
      job: "ansible-pull -U https://github.com/austozi/selfhosted RaspberryPiOS/default.yml"
      minute: "0"
      user: root
