- hosts: localhost
  become: true
  tasks:
  
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes    
      
  - name: Install packages
    package:
      name:
        - ansible
        - curl
        - docker-ce        
        - docker-compose
        - git
        - python3-pip
      state: latest    
      
  - name: Install/Update Python modules
    pip:
      name:
        - pip
        - yt-dlp
      state: latest
