version: "2.4"
services:
  watchtower:
    image: docker.io/containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      TZ: Europe/London
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "false"
      WATCHTOWER_INCLUDE_STOPPED: "false"
      WATCHTOWER_REVIVE_STOPPED: "false"
      WATCHTOWER_SCHEDULE: "0 0 5 * * *"
      WATCHTOWER_NO_RESTART: "false"
      WATCHTOWER_NO_PULL: "false"
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: "watchtower@example.com" # Change me
      WATCHTOWER_NOTIFICATION_EMAIL_TO: "admin@example.com" # Change me
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "smtp.example.com" # Change me
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587 # Change me
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "watchtower@example.com" # Change me
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "watchtower_password" # Change me
      # If using Gotify, change WATCHTOWER_NOTIFICATIONS to 'gotify'.
      # Uncomment and specify the following parameters for Gotify. 
      # Also, comment out email-related parameters above.
      # Generate the token from within Gotify, under Apps > Create Application.
      # WATCHTOWER_NOTIFICATION_GOTIFY_URL: https://gotify.example.com # Change me
      # WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: Super-Secret-Token # Change me
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.4.0/29
