services:
  pigallery:
    image: docker.io/bpatrik/pigallery2:latest-alpine
    container_name: pigallery2
    restart: unless-stopped
    environment:
      TZ: Europe/London
      NODE_ENV: production
    volumes:
      - ./config:/app/data
      - ./data:/app/data/images:ro
    networks:
      - frontend
networks:
  frontend:
