version: "3"
services:
  freshrss:
    image: "linuxserver/freshrss:latest"
    container_name: "freshrss"
    restart: "unless-stopped"
    environment:
      PUID: 1001
      GUID: 1001
      TZ: "Europe/London"      
    volumes:
      - "./config:/config"
    expose:
      - 80
    networks:
      - "proxy"
      - "mailer"
networks:
  proxy:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.16.25.0/29"
  mailer:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.16.26.0/29"
