version: "2.4"
services:
  fdroid:
    image: docker.io/austozi/fdroidserver:latest
    container_name: fdroid
    restart: unless-stopped
    command: >
      sh -c "apachectl -D FOREGROUND & fdroid init || true && fdroid update -c && sleep 1h"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/www:/var/www/html
      - ./config/log:/var/log/apache2
    expose:
      - 80
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.9.0/29
