version: "3"
services:
  fdroid:
    image: docker.io/austozi/fdroidserver:latest
    container_name: fdroid
    restart: unless-stopped
    environment:
      PUID: 1000
      GUID: 1000
      TZ: Europe/London
    volumes:
      - ./config/www:/var/www/html
      - ./config/log:/var/log/apache2
    expose:
      - 80
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.49.0/29
