services:
  manyfold:
    image: ghcr.io/manyfold3d/manyfold-solo:latest
    container_name: manyfold
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      MULTIUSER: enabled 
    env_file: 
      - ./.env
    volumes:
      - ./config:/config
    expose:
      - 3214
    networks:
      - frontend
networks:
  frontend:
